server:
  port: 8089

spring:
  application:
    name: library
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:./db/library;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: sa
    password:
  liquibase:
    change-log: classpath:/db/changelog/master.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: create
